Add responsiveness to navigation menu
kamilwilk95/wdp-2204-02 pull request #18
Opened 2022-04-22 13:00 UTC by cayceworld

2022-04-22 18:44 UTC, bsz3636 reviewed
Na tabletach widzę, że jest w porządku. Wyszukiwanie jest pod menu. Na mniejszych ekranach pojawia się ikonka menu tak jak miało być.  Przy rozwinięciu pojawia się jednak problem (menu nie jest widoczne w całości i jest chyba za nisko).  
https://responsivetesttool.com/

2022-04-24 13:32 UTC, kamilwilk95 requested changes

2022-04-24 13:32 UTC, kamilwilk95 commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    @media (max-width: 767px) {
Użyjmy mixinów

2022-04-24 13:32 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    height: 45px;
nie używajmy sztywnej wysokosci, line height + padding = wysokość :)

2022-04-24 13:32 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +@media (max-width: 494px){
Mixins please

2022-04-26 12:34 UTC, kamilwilk95 approved these changes

2022-04-27 16:05 UTC, bsz3636 approved these changes

2022-04-28 04:54 UTC, merged