Wdp220402 22
kamilwilk95/wdp-2204-02 pull request #20
Opened 2022-04-24 14:26 UTC by bsz3636

2022-04-25 22:00 UTC, MaciekLichon reviewed
Wydaje mi się, że jedyne czego brakuje to ramka wokół kontenera hot deals. 

@kamilwilk95 jeszcze odnośnie pobierania danych ze stanu to chciałem zapytać (w odniesieniu do swojego zadania) czy to co zrobiła Beata czyli import initialState (bez selektorow i akcji) to jest to, co było oczekiwane pod poleceniem ", a treści pobierać ze stanu aplikacji."? W takim razie chyba się trochę rozpędziłem u siebie.

2022-04-26 12:23 UTC, cayceworld requested changes
Widzę że brakuję kropek obok "HOT DEALS" i sam napis jest nie ma lewego paddingu. 
Reszta warunków zostały spełnione.

2022-04-26 12:24 UTC, kamilwilk95 requested changes
Są różnice między implementacją a projektem. Brakuje obramowania na sekcji po lewej stronie.

2022-04-26 12:24 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +import initialState from '../../../redux/initialState';
Tak nie odczytujemy stanu, zapoznaj się z hookiem `useSelector`

2022-04-26 12:24 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +                  <a className={styles.active} href='#' > </a>
Nie potrzebne spacje

2022-04-26 12:24 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +              src={`${process.env.PUBLIC_URL}/images/products/Aenean Ru Bristique 8.jpg`}
W nazwie pliku nie używajmy spacji, nazwa pliku niech będzie w store

2022-04-26 12:25 UTC, kamilwilk95 commented
Maciek ma rację, nie importujemy initialState tylko używamy hooka useSelector

2022-04-27 12:56 UTC, kamilwilk95 requested changes

2022-04-27 12:56 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +  const products = useSelector (state => getAll (state));
Nadal używasz spacji w niedozwolonych miejscach

2022-04-27 14:49 UTC, bsz3636 commented on src/components/features/Promoted/Promoted.js
> +  const products = useSelector (state => getAll (state));
Chciałabym aby kod był czytelniejszy i jak widać czasami przesadzam ;) Mam nadzieję, że wszystkie już poprawiłam.

2022-04-28 05:20 UTC, kamilwilk95 requested changes
Do tych spacji najlepiej użyć autoformatowania ;)

2022-04-28 05:20 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +              <div className={clsx(styles.hotDeals, 'col' )}>
spacja po 'col'

2022-04-28 05:20 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +                    <a className={styles.active} href='#' > </a>
nadal spacje

2022-04-28 05:20 UTC, kamilwilk95 commented on src/components/features/Promoted/Promoted.js
> +                    <a href='#' > </a>
spacje

2022-04-28 15:41 UTC, bsz3636 commented on src/components/features/Promoted/Promoted.js
> +                    <a href='#' > </a>
Chyba już wszystkie ;)

2022-04-28 18:16 UTC, kamilwilk95 approved these changes

2022-04-29 12:11 UTC, merged