WDP220402-27
kamilwilk95/wdp-2204-02 pull request #21
Opened 2022-04-25 19:59 UTC by MaciekLichon

2022-04-25 20:32 UTC, bsz3636 approved these changes

2022-04-26 12:33 UTC, kamilwilk95 requested changes

2022-04-26 12:33 UTC, kamilwilk95 commented on src/redux/initialState.js
> +      galleryCategory: 'topSeller',
to nie brzmi jak coś co może być wykorzystane tylko w galerii, ja bym to nazwał `tags`

2022-04-26 12:33 UTC, kamilwilk95 commented on src/components/features/Gallery/Gallery.js
> +const Gallery = () => {
Ten komponent jest ogromny, przez co nie czytelny, trudny w rozwoju i nie mozna go używać ponownie. Galeria sama w sobie powinna być osobnym komponentem. Sekcja po prawej stronie osobnym.

2022-04-26 12:33 UTC, kamilwilk95 commented on src/components/features/Gallery/Gallery.js
> +  const [activeGallery, setActiveGallery] = useState(galleryCategories[0]);
to activeGallery czy activeCategory?

2022-04-26 12:33 UTC, kamilwilk95 commented on src/components/features/Gallery/Gallery.js
> +  const nextSlide = e => {
Takie akcje powinny byc w osobnym komponencie galerii, który byłby uniwersalny

2022-04-27 13:00 UTC, kamilwilk95 requested changes

2022-04-27 13:00 UTC, kamilwilk95 commented on src/components/features/GallerySelect/GallerySelect.js
> +            <Button variant='outline' onClick={toggleCompare} className={clsx(styles.actionButton, styles.tooltip, selectedProduct.comparing && styles.comparing)}>
tooltip pasuje wynieść do osobnego komponentu

2022-04-27 13:00 UTC, kamilwilk95 commented on src/components/features/GallerySelect/GallerySelect.js
> +          <div className={styles.ratingBox}>
już mamy miejsce w którym jest rating, wynieśmy z tamtą rating do osobnego komponentu i użyjmy też tutaj

2022-04-27 20:54 UTC, MaciekLichon commented on src/components/features/GallerySelect/GallerySelect.js
> +          <div className={styles.ratingBox}>
chodzi Ci tutaj o polaczenie gwiazdek i nazwy produktu w jeden komponent? div ostylowany na ratingBox wystepuje tylko w galerii i jest to ten caly prostokat z czarnymi naroznikami itd. Wewnatrz wykorzystalem komponent ProductRating ale on oblusguje tylko gwiazdki

2022-04-28 05:38 UTC, kamilwilk95 commented on src/components/features/GallerySelect/GallerySelect.js
> +          <div className={styles.ratingBox}>
tak, chodzi mi tylko o gwiazdki, bez nazwy

2022-04-28 10:30 UTC, MaciekLichon commented on src/components/features/GallerySelect/GallerySelect.js
> +          <div className={styles.ratingBox}>
To to dodałem właśnie w comicie „add rating” i w linijce 134 jest wywołany komponent „productRating”

2022-04-28 18:15 UTC, kamilwilk95 approved these changes

2022-04-28 18:16 UTC, merged