Wdp220402 29
kamilwilk95/wdp-2204-02 pull request #29
Opened 2022-05-01 19:10 UTC by MaciekLichon

2022-05-02 05:50 UTC, bsz3636 reviewed
Slider miniaturek nie przewija się za pomocą komponentu Swipeable

2022-05-02 10:13 UTC, kamilwilk95 requested changes
Na tabletach wygląda to średnio bardzo jeszcze, może daj zdjęcie po prawej na górę a galerię na dół

2022-05-03 00:05 UTC, bsz3636 approved these changes

2022-05-03 07:35 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/166418456-71c1a054-64f3-4f7c-8c85-d0071199d723.png)
Tutaj to nie wygląda dobrze

2022-05-03 07:35 UTC, kamilwilk95 commented on src/components/features/GalleryAdvert/GalleryAdvert.module.scss
> +@include for-tablet {
Ale w zadaniu nie było nic o ukrywaniu tego elementu na tabletach, on musi być, tylko czytelniej.

2022-05-03 09:54 UTC, kamilwilk95 approved these changes

2022-05-03 09:54 UTC, merged